pipeline{
    agent any
    stages{
        stage("Deploy"){
            steps{
                retry (3) {
                    sh "========executing build========"
                }

                timeout(time: 3, unit: 'SECONDS') {
                    sh 'sleep 5'
                }
            }
        }
    }
}
