version: "3.9"

services:
    jenkins:
        container_name: jenkins
        image: jenkins-ansible
        build:
            context: jenkins-ansible
        ports:
            - "8081:8080"
        volumes:
            - "./jenkins_home:/var/jenkins_home"
            - "./jenkins-ansible:/var/jenkins_home/ansible"
        networks:
            - net
    remote_host:
        container_name: remote-host
        image: remote-host
        build:
            context: centos
        volumes:
            - "./scripts/backup-sql.sh:/tmp/script.sh"
        networks:
            - net
    db_host:
        container_name: db
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - "MYSQL_ROOT_PASSWORD=example"
        volumes:
            - "$PWD/db_data:/var/lib/mysql"
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        networks:
            - net
    web:
        container_name: web
        image: ansible-web
        build:
            context: jenkins-ansible/web
        ports:
            - "8082:80"
        networks:
            - net
networks:
    net:
